name: Bug report
description: Report a bug and help improve the module
title: "[BUG] Don't forget to write a meaningful title"
labels: bug
assignees: mnaoumov
body:
  - type: markdown
    attributes:
      value: |
        ## Bug report

        > [!WARNING]
        >
        > Incomplete, vague, or poorly described bug reports will be closed.
        >
        > The bug report and all attachments must be in English. Non-English bug reports will be closed.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the bug. Include any relevant details.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide a step-by-step description.
      placeholder: |
        1. Run '...'
        2. Notice that '...'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages if available.
    validations:
      required: true
  - type: input
    attributes:
      label: Module version
      description: ⚠️ Must be the latest version. If not, explain why above.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: PowerShell version
      description: Output of $PSVersionTable.PSVersion
      placeholder: 5.1.19041.1
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      placeholder: Windows 10
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: Attach screenshots or logs if applicable.
      placeholder: Drag and drop files here.
  - type: checkboxes
    attributes:
      label: Confirmations
      description: Ensure the following conditions are met
      options:
        - label: I have checked the module's GitHub repository and haven't found any similar bugs
          required: true
